#ifndef ROBOT_SERIAL_SENTRY_MSG_H
#define ROBOT_SERIAL_SENTRY_MSG_H

#include "robot_serial/msg/action.hpp"
#include "robot_serial/msg/decision.hpp"
#include "robot_serial/msg/info.hpp"
#include "robot_serial/msg/map.hpp"
#include "robot_serial/msg/velocity.hpp"
#include "robot_serial/msg/whitelist.hpp"
#include "robot_serial/msg/buff.hpp"
#include "robot_serial/msg/dartinfo.hpp"
#include "robot_serial/msg/event.hpp"
#include "robot_serial/msg/gameresult.hpp"
#include "robot_serial/msg/gamestatus.hpp"
#include "robot_serial/msg/hp.hpp"
#include "robot_serial/msg/hurtdata.hpp"
#include "robot_serial/msg/interaction.hpp"
#include "robot_serial/msg/mapcommand.hpp"
#include "robot_serial/msg/projectileallowance.hpp"
#include "robot_serial/msg/refereewarning.hpp"
#include "robot_serial/msg/rfidstatus.hpp"
#include "robot_serial/msg/robotp.hpp"
#include "robot_serial/msg/robotposition.hpp"
#include "robot_serial/msg/robotstatus.hpp"
#include "robot_serial/msg/sentryinfo.hpp"
#include "robot_serial/msg/supplyprojectile.hpp"
#include "robot_serial/msg/switch.hpp"

#endif //ROBOT_SERIAL_SENTRY_MSG_H