#0x020B topic:/robot/robotposition
float32 hero_x#己方英雄机器人位置 x 轴坐标，单位：m
float32 hero_y#己方英雄机器人位置 y 轴坐标，单位：m
float32 engineer_x#己方工程机器人位置 x 轴坐标，单位：m
float32 engineer_y#己方工程机器人位置 y 轴坐标，单位：m
float32 standard_3_x#己方 3 号步兵机器人位置 x 轴坐标，单位：m
float32 standard_3_y#己方 3 号步兵机器人位置 y 轴坐标，单位：m
float32 standard_4_x#己方 4 号步兵机器人位置 x 轴坐标，单位：m
float32 standard_4_y#己方 4 号步兵机器人位置 y 轴坐标，单位：m
float32 standard_5_x#己方 5 号步兵机器人位置 x 轴坐标，单位：m
float32 standard_5_y#己方 5 号步兵机器人位置 y 轴坐标，单位：m